name: RefontSocialExtended
version: '1.4.0-extended'
main: ru.rizonchik.refontsocial.RefontSocial
api-version: '1.16'
softdepend: [PlaceholderAPI, ProtocolLib]

commands:
  reputation:
    aliases: [rep, rating, social]
    description: Reputation / Social rating
    usage: /rep help
  repreload:
    description: Reload RefontSocial config/files
    usage: /repreload
    permission: refontsocial.admin
  marry:
    aliases: [marriage]
    description: Marriage system command
    usage: /marry help
    permission: refontsocial.marry.use
  gender:
    aliases: [sex]
    description: Gender profile command
    usage: /gender help
    permission: refontsocial.gender.use
  sit:
    aliases: [сидеть]
    description: Sit on the ground
    usage: /sit
    permission: refontsocial.sit.use
  friends:
    aliases: [friend]
    description: Friends system command
    usage: /friends
    permission: refontsocial.friends.use

permissions:
  refontsocial.use:
    default: true
  refontsocial.admin:
    default: op
  refontsocial.bypass.cooldown:
    default: op
  refontsocial.bypass.interaction:
    default: op
  refontsocial.bypass.ip:
    default: op
  refontsocial.marry.use:
    default: true
  refontsocial.gender.use:
    default: true
  refontsocial.sit.use:
    default: true
  refontsocial.friends.use:
    default: true
